---
title: "Ch21"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
---

## Exercises 27.2.1
Create a new notebook using File > New File > R Notebook. Read the instructions. Practice running the chunks. Verify that you can modify the code, re-run it, and see modified output.

--

Create a new R Markdown document with File > New File > R Markdown… Knit it by clicking the appropriate button. Knit it by using the appropriate keyboard short cut. Verify that you can modify the input and see the output update.

--

Compare and contrast the R notebook and R markdown files you created above. How are the outputs similar? How are they different? How are the inputs similar? How are they different? What happens if you copy the YAML header from one to the other?

The `YAML` is the same but the `output` is set to to `html_notebook`. To switch between the two docs you only have to change the format in `output`. As for the document, `notebooks` offer to show the code as drop down chunks, a feature which Rmarkdowns don't have.

Create one new R Markdown document for each of the three built-in formats: HTML, PDF and Word. Knit each of the three documents. How does the output differ? How does the input differ? (You may need to install LaTeX in order to build the PDF output — RStudio will prompt you if this is necessary.)

--

## Exercises 27.3.1

Practice what you’ve learned by creating a brief CV. The title should be your name, and you should include headings for (at least) education or employment. Each of the sections should include a bulleted list of jobs/degrees. Highlight the year in bold.

```
---
title: "My CV"
output: html_document
---

##  Jorge Cimentada
##  cimentadaj@gmail.com

# Education
- PhD in **Quantitative Sociology**
- Master's in Demography and Sociology
- B.A in Business


# Employment
- Data Scient at RECSM
- Data Analyst at UPF
- Junior Analyst at Newlink

Skills: R, Python, Git, SQL, LaTeX and Stats

```


Using the R Markdown quick reference, figure out how to:

Add a footnote.

`Here's a footnote [^1]`

And add footnote below:

`[^1]: Here's a footnote`

Add a horizontal rule.

Add `--------`

Add a block quote.

Something like `> This is a quote`

Copy and paste the contents of diamond-sizes.Rmd from https://github.com/hadley/r4ds/tree/master/rmarkdown in to a local R markdown document. Check that you can run it, then add text after the frequency polygon that describes its most striking features.

--

## Exercises 27.4.7

Add a section that explores how diamond sizes vary by cut, colour, and clarity. Assume you’re writing a report for someone who doesn’t know R, and instead of setting echo = FALSE on each chunk, set a global option.

Download diamond-sizes.Rmd from https://github.com/hadley/r4ds/tree/master/rmarkdown. Add a section that describes the largest 20 diamonds, including a table that displays their most important attributes.

Modify diamonds-sizes.Rmd to use comma() to produce nicely formatted output. Also include the percentage of diamonds that are larger than 2.5 carats.

For the answers of the three previous exercises, see the answer `26.3` [here](https://jrnold.github.io/r4ds-exercise-solutions/r-markdown.html)

Set up a network of chunks where d depends on c and b, and both b and c depend on a. Have each chunk print lubridate::now(), set cache = TRUE, then verify your understanding of caching.